name: Auto Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            cd /home/ipul/my-node-app
            git pull origin main

            # Build Docker image terbaru
            docker build -t my-node-app:latest .

            # Cek apakah container sudah ada
            if [ $(docker ps -a -q -f name=my-node-app-container) ]; then
              echo "Container sudah ada, cukup restart"
              docker stop my-node-app-container
              docker rm my-node-app-container
              docker run -d -p 5028:5028 --name my-node-app-container my-node-app:latest
            else
              echo "Container belum ada, buat baru"
              docker run -d -p 5028:5028 --name my-node-app-container my-node-app:latest
            fi